name: Publish to Sigrid
on:
  push:
    branches:
      - master

jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@main
        with:
          customer: ssm
          system: feiyang-test
          publishonly: true
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
